changelog:
  categories:
    - title: Features
      labels:
        - feature
        - enhancement
        - feat
    - title: Fixes
      labels:
        - fix
        - bug
        - bugfix
    - title: Performance
      labels:
        - perf
        - performance
        - optimization
    - title: Documentation
      labels:
        - docs
        - documentation
    - title: Maintenance
      labels:
        - chore
        - refactor
        - ci
        - build
    - title: Other Changes
      labels:
        - "*"
